### PR TITLE
Port HIL tests to pytest

### PR DESCRIPTION
**Pull request by ACascarino**
Work on closing #224 
Working in parallel with development work on xmos/test_support, which this will depend on

### CODE REVIEW

**Comment by ACascarino** [comment]
Hi team - have finished up porting lib_i2c and would love some thoughts on style/approach before I start tackling the other ones!
Very happy to talk about what approach has been taken etc. so if there are any thoughts please do let me know

**Comment by xmos-jmccarthy** [comment]
Adding @keithm-xmos for input on the documentation check failures.

**Comment by keithm-xmos** [comment]
I simply re-ran the docs job and the link checking worked.  Something took too long to reply the first time around.

**Comment by ACascarino** [comment]
Okay then!

This is ready for review - I've put documentation on how to set up the test environment [on Confluence](https://xmosjira.atlassian.net/wiki/spaces/~228098649/pages/3335061521/). In order to run the tests you'll need to grab the `cmake_additions` [branch of my fork of](https://github.com/ACascarino/test_support/tree/cmake_additions) `test_support` instead of the current develop branch of the XMOS repo.

**Review by keithm-xmos — APPROVED** [review]
I believe this is ready to merge.  @xmos-jmccarthy?

**Pull request merged**
