### PR TITLE
Feature/dfu

### LINKED ISSUE #551: Explorer board 2v0 bsp_config does not support flash writes
**System information**
 - OS: All
 - xcore board: Explorer
 - All that include explorer board 2v0 from initial addition to at least c6679cf5e2f53ebf8d789059a0cd4dd0b12ec8be

**Describe the current behavior**
Flash writes will fail to work

**Describe the expected behavior**
Flash writes should work

**Standalone code to reproduce the issue**
Not needed

**Other info or logs** 
The flash part used in the 1V0-1V2 boards had the programming done with command over SDO0, and addr + data over data lines.
https://github.com/xmos/fwk_rtos/blob/79f265cf84046826987d7eb850840870011e275e/modules/bsp_config/XCORE-AI-EXPLORER_2V0/platform/platform_init.c#L83
The 2V0 flash part requires command and addr over SDIO0 and data over data lines.
qspi_flash_page_program_1_4_4 should be replaced with qspi_flash_page_program_1_1_4 for uses with the Explorer Board 2V0

### PR DESCRIPTION
**Pull request by xmos-jmccarthy**
Add DFU example over USB.

Uses a new DFU image driver, which utilized libquadflash at boot to create an image table for the app to use.

Closes #551

### CODE REVIEW

**Comment by xmos-jmccarthy** [comment]
Marking do not merge.
TODO:
Update readme
Resolve rtos submodule conflict.
Add cmake command to create upgrade image
Add cmake command to flash with factory image

**Review by keithm-xmos — APPROVED** [review]
Rubber stamp

**Comment by keithm-xmos** [comment]
I noticed that the RTOS core examples do not build.  

https://github.com/xmos/xcore_sdk/actions/runs/3440356711/jobs/5738743733

I wonder if this is because the Docker builder uses XTC 15.1.0.  We need to update to a newer version but that may be a couple weeks away.

**Comment by xmos-jmccarthy** [comment]
Do not merge yet.  Adding DFU support for Tools 15.1.4.

**Comment by xmos-jmccarthy** [comment]
Moved QSPI spec out of DFU driver to allow users to have more flexibility.  This enables support for Tools 15.1.3 and 15.1.4 at the cost of a little extra explicit initialization code.

Tested on Linux with 15.1.3, 15.1.4, and 15.2.0.

**Comment by xmos-jmccarthy** [comment]
#553 
All OS verified.

Readme updated for potential Windows FAQ.

**Pull request merged**
