### PR TITLE
fixed flash_image script in cifar10 example

### PR DESCRIPTION
**Pull request by notplus**
fixed "cp: cannot stat 'image_n0c1.swmem': No such file or directory" error

### CODE REVIEW

**Comment by xmos-jmccarthy** [comment]
Could you please provide some information on what you were doing that caused this issue?

**Comment by notplus** [comment]
The error  `cp: cannot stat 'image_n0c1.swmem': No such file or directory` occurred when I executed command `./flash_image.sh -s` followed by [README](https://github.com/xmos/xcore_sdk/tree/main/examples/freertos/cifar10). It seems that the file `image_n0c1.swmem` already exists in right path, so it's no need to copy the file.

**Comment by xmos-jmccarthy** [comment]
If the binary has not been built, the script will cause an error on:
`cp image_n0c1.swmem ../../filesystem_support`

If you had removed this line, when dd is called to combine the filesystem and swmem, the script will succeed, but you will end up flashing a file that is missing the model in swmem format.
`cat fat.fs | dd of=image_n0c1.swmem bs=1 seek=1048576 conv=notrunc`

Have you run on hardware?

**Comment by notplus** [comment]
Ok, I got it. After the script running `xobjdump --strip cifar10_1.xe` and `xobjdump --split cifar10_1.xb ` commands, the file `image_n0c1.swmem` didn't generate and caused an copy error. But it worked well on hardware. And I am sure that the binary has been built. Is there anything wrong?

**Comment by xmos-jmccarthy** [comment]
How did you build your binary?

There are 3 configurations which control where the model is stored.  SRAM, Flash (swmem), and DDR (extmem).  The flash_image.sh script is responsible for flashing the filesystem volume, containing the test images, and in the case of a swmem build, putting the model into flash.

The flash_image.sh script should be called with -s for a binary that has been built with swmem, ie:
`$ make BOARD=$TARGET USE_SWMEM=1`

If you built with the model in sram or extmem, you only need to flash the filesystem and can use:
`$ ./flash_image.sh -f`

**Comment by notplus** [comment]
I just followed the [README](https://github.com/xmos/xcore_sdk/tree/main/examples/freertos/cifar10) to use swmem.
```shell
make BOARD=XCORE-AI-EXPLORER USE_SWMEM=1
./flash_image.sh -f
```

**Comment by xmos-jmccarthy** [comment]
Could you provide me the two build reports?  There will be one for each tile build.  They both should look like:
```
Constraint check for tile[0]:
  Memory available:       524288,   used:      xxxxxx .  OKAY
    (Stack: xxxxx, Code: xxxxx, Data: xxxxx)
  SwMem available:    1073741824,   used:          xxxxx .  OKAY
    (Stack: 0, Code: 0, Data: 0)
Constraints checks PASSED.
Constraint check for tile[1]:
  Memory available:       524288,   used:      xxxxx .  OKAY
    (Stack: xxxxx, Code: xxxxx, Data: xxxxx)
  SwMem available:    1073741824,   used:      xxxxx .  OKAY
    (Stack: 0, Code: 0, Data: xxxxx)
Constraints checks PASSED WITH CAVEATS.
```

Are you using the provided model, or did you convert a different one over?

**Comment by xmos-jmccarthy** [comment]
Oh, actually, have you built this project previously with a different set of flags?

Because the cmake variables are stored in the cache, it is possible that you built the sram or extmem build despite passing make the swmem flag.

If you want to build a different configuration, you should run
`$ make distclean`

**Comment by notplus** [comment]
Ok, it just needs to execute `make distclean`. Thank you for your nice reply. :+1:

**Pull request closed without merging**
