### PR TITLE
Fix XMOS_TOOL_PATH variable in the cmake toolchain file

### PR DESCRIPTION
**Pull request by danielpieczko**
Noticed this while using the xcore_sdk toolchain in sw_avona. The environment variable that the tools sets is `XMOS_TOOL_PATH` instead of `XMOS_TOOLS_PATH`.

### CODE REVIEW

**Review by keithm-xmos — APPROVED** [review]
Nice catch!

**Comment by xmos-jmccarthy** [comment]
This was the optional include added to allow someone to override the tools to use.  The naming was intentional.

**Comment by danielpieczko** [comment]
Thank you for the correction, we can drop this change then if it's intentional.

**Comment by xmos-jmccarthy** [comment]
We might want to consider renaming it to avoid confusion.

By default the SDK will use the tools it finds on PATH.  By passing cmake XMOS_TOOL_PATH, you can specify specific tools to use, potentially only useful to XMOS developers who test new versions of tools.

The XTC ENV will setup XMOS_TOOLS_PATH, which points to the tools version installed.  The fact these are named similarly might bring about confusion.

**Comment by keithm-xmos** [comment]
@xmos-jmccarthy last paragraph has a typo I think.  The XTC ENV will setup XMOS_TOOL_PATH, which points to the tools version installed. He is correct about the reason we have a different envar in the SDK.  I will add a comment in the file so the next person is not also confused.

**Pull request closed without merging**
